print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill?\n"))
percentage = int(input("What percentage tip would you like to give? 10, 12 or 15\n"))
people = int(input("How many poeple to split the bill?\n"))
score = round((total_bill / people) * (1 + (percentage / 100)), 2)
total_tip = print(f"Each person should pay: {score}")
